REM GENRE "Hard Rock"
REM DATE 1990
REM DISCID 840A130A
REM COMMENT "ExactAudioCopy v0.95b4"
CATALOG 1234567890123
CDTEXTFILE FILENAME.CDT
PERFORMER "Doro"
TITLE "Doro"
FILE "Doro - Doro.ape" WAVE
  TRACK 01 AUDIO
    TITLE "Unholy Love"
    PERFORMER "Doro"
  TRACK 02 AUDIO
    TITLE "I Had Too Much to Dream"
    PERFORMER "Doro"
    FLAGS 4CH PRE DCP SCMS
